#!/usr/bin/env ansible-playbook
---
- hosts: pi 
  gather_facts: yes
  vars:
    update_cache: yes
    packages_to_install: [ git, automake, build-essential, 
        npm, python3-pip, python3-dev, vim, 
        libusb-dev, libdbus-1-dev, libglib2.0-dev, libudev-dev, 
        libical-dev, libreadline-dev, cmake
        ]
    key_location: /home/xpalant/.ssh/id_rsa
    ssh_config_location: /home/xpalant/.ssh/config
    sshd_config_file: /home/xpalant/tools/testbed-ansible/template/sshd_config
  tasks:
    - name: update and upgrade 
      apt: 
        upgrade: safe
      become: true

    - name: install apt packages
      apt: 
        name: "{{ packages_to_install }}"
        state: latest
        update_cache: "{{ update_cache }}"
      become: true

    - name: download intel iot   
      git: repo=https://github.com/intel-iot-devkit/tinyb.git dest=/home/pi/tinyb
      register: gitclone

    - name: create and change directory for intel iot
      file:
        path: /home/pi/tinyb/build
        state: directory
        owner: pi
        mode: 0755

    - name: compile intel iot
      become: true
      shell: cd /home/pi/tinyb/build && cmake .. && make && make install
      when: gitclone.changed

        
    - name: give ssh key to all
      become: true
      copy:
        src: "{{ key_location }}"
        dest: /home/pi/.ssh/id_rsa
        mode: 0600
        owner: pi
        group: pi
        backup: yes


    - name: give ssh config file to all
      copy:
        src: "{{ ssh_config_location }}"
        dest: /home/pi/.ssh/config
        owner: pi
        group: pi
        backup: yes

    - name: change sshd_config to prevent root login and pw auth.
      become: true
      copy:
        src: "{{ sshd_config_file }}"
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        backup: yes

