#!/usr/bin/env ansible-playbook
---
- hosts: pi
  gather_facts: yes

  tasks:
    - name: wlan settings
      become: true
      template:
        src: template/interfaces.j2
        dest: /etc/network/interfaces
        backup: true
      register: configdone

    - name: restart network service
      become: true
      service:
        name: networking
        state: restarted
      when: configdone.changed


